name: Test and Lint

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v4.2.0 # use the explicit version number
        with:
          build: npm run build
          start: npm start

      - name: Print the final result
        shell: bash
        run: |
          echo "## Coverage Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a line

      - name: Run Coverage
        run:  npm run coverage


      - name: Code Coverage Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage/cobertura-coverage.xml
          badge: true
          fail_below_min: true
          format: markdown
          hide_branch_rate: false
          hide_complexity: true
          indicators: true
          output: both
          thresholds: '60 80'
      - run: |
         cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY # add on action summary

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2.3.1
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md

      # save nyc report
      - name: save coverage report
        uses: actions/upload-artifact@v3
        with:
          name: nyc-report
          if-no-files-found: error
          path: .nyc_output/out.json

  coverage:
    runs-on: ubuntu-latest
    needs: cypress-run
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: download nyc report
        uses: actions/download-artifact@v3
        with:
          name: nyc-report

      - name: Print the final result
        shell: bash
        run: |
          value=`yarn run coverage`
          echo The result is $value

